export default function loremImpus() {
    return [`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Ornare lectus sit amet est. Et netus et malesuada fames ac turpis. Nibh praesent tristique magna sit amet. Tortor id aliquet lectus proin nibh nisl condimentum id. Auctor urna nunc id cursus metus aliquam eleifend. Urna nec tincidunt praesent semper feugiat nibh. Morbi tempus iaculis urna id volutpat lacus. Risus commodo viverra maecenas accumsan. Dui vivamus arcu felis bibendum ut tristique et. In hac habitasse platea dictumst. Dui faucibus in ornare quam viverra orci sagittis eu. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin. Accumsan in nisl nisi scelerisque eu ultrices. Malesuada proin libero nunc consequat interdum varius sit amet. Neque laoreet suspendisse interdum consectetur libero id faucibus.Sed turpis tincidunt id aliquet. Arcu dictum varius duis at consectetur lorem donec. Dui id ornare arcu odio ut sem nulla pharetra. Elit pellentesque habitant morbi tristique senectus et. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Elementum facilisis leo vel fringilla est ullamcorper eget. Est pellentesque elit ullamcorper dignissim cras tincidunt. At urna condimentum mattis pellentesque id. Amet porttitor eget dolor morbi non arcu risus quis. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Orci a scelerisque purus semper eget duis at. Urna neque viverra justo nec ultrices dui. Aliquam faucibus purus in massa tempor. Egestas fringilla phasellus faucibus scelerisque. Maecenas sed enim ut sem viverra. Ipsum dolor sit amet consectetur adipiscing.
    Purus semper eget duis at tellus at. Nibh praesent tristique magna sit amet purus. In aliquam sem fringilla ut morbi tincidunt augue. Blandit turpis cursus in hac habitasse platea dictumst quisque. Eget sit amet tellus cras adipiscing enim eu. Sit amet dictum sit amet justo donec. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Condimentum mattis pellentesque id nibh tortor id aliquet. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Pharetra massa massa ultricies mi quis hendrerit dolor. Diam volutpat commodo sed egestas egestas fringilla. Duis ut diam quam nulla porttitor. Erat velit scelerisque in dictum non consectetur a erat. Turpis tincidunt id aliquet risus feugiat in ante. Ornare arcu odio ut sem. Suspendisse in est ante in nibh mauris. Neque sodales ut etiam sit amet nisl purus. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Suscipit adipiscing bibendum est ultricies integer quis. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat.Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Amet facilisis magna etiam tempor. Est sit amet facilisis magna etiam. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Sed risus ultricies tristique nulla aliquet enim tortor at. Massa massa ultricies mi quis hendrerit dolor magna eget. In metus vulputate eu scelerisque felis imperdiet proin. Nisi quis eleifend quam adipiscing vitae. Leo a diam sollicitudin tempor id eu nisl nunc mi. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Integer eget aliquet nibh praesent tristique magna sit amet purus. Lorem ipsum dolor sit amet. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Auctor neque vitae tempus quam pellentesque nec nam.
    
    A diam maecenas sed enim ut sem viverra aliquet eget. Interdum varius sit amet mattis vulputate enim nulla aliquet. Nulla facilisi cras fermentum odio eu. Elit sed vulputate mi sit amet mauris. Amet justo donec enim diam vulputate ut pharetra. Praesent tristique magna sit amet purus gravida. At varius vel pharetra vel. Blandit turpis cursus in hac. Morbi tempus iaculis urna id volutpat lacus laoreet. Est placerat in egestas erat imperdiet sed. Id diam maecenas ultricies mi eget. Sem fringilla ut morbi tincidunt augue interdum velit.
    
    Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Mauris sit amet massa vitae tortor condimentum. Non quam lacus suspendisse faucibus. Vitae sapien pellentesque habitant morbi tristique senectus et. Feugiat nisl pretium fusce id velit ut tortor pretium. Pretium viverra suspendisse potenti nullam. Proin sed libero enim sed faucibus turpis in eu. Ut consequat semper viverra nam libero justo laoreet sit amet. Nullam eget felis eget nunc lobortis mattis aliquam. Mi bibendum neque egestas congue quisque. Porttitor lacus luctus accumsan tortor posuere.
    
    Feugiat pretium nibh ipsum consequat nisl. Vitae semper quis lectus nulla at volutpat diam ut. Sed faucibus turpis in eu mi bibendum neque egestas congue. Tempus egestas sed sed risus pretium quam. Etiam erat velit scelerisque in dictum. Sagittis eu volutpat odio facilisis. Tincidunt augue interdum velit euismod in pellentesque. Augue interdum velit euismod in pellentesque. Dui id ornare arcu odio ut sem nulla. Ut pharetra sit amet aliquam id diam maecenas ultricies. At varius vel pharetra vel turpis nunc. Gravida rutrum quisque non tellus orci.
    
    Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Laoreet suspendisse interdum consectetur libero id. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Tellus at urna condimentum mattis pellentesque id nibh tortor. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Eget dolor morbi non arcu risus quis varius. Est lorem ipsum dolor sit amet consectetur. Eget aliquet nibh praesent tristique magna. Sapien pellentesque habitant morbi tristique senectus et netus. Ultrices dui sapien eget mi proin sed libero. Massa placerat duis ultricies lacus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Vitae justo eget magna fermentum iaculis eu non diam.
    `,
    `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu sem integer vitae justo. Aliquet nec ullamcorper sit amet risus. Adipiscing enim eu turpis egestas pretium aenean. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Neque convallis a cras semper. Sed arcu non odio euismod lacinia at quis risus. In nibh mauris cursus mattis. Et sollicitudin ac orci phasellus egestas tellus. At ultrices mi tempus imperdiet nulla.

Scelerisque purus semper eget duis. Lacinia at quis risus sed vulputate. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Felis eget velit aliquet sagittis id consectetur. Turpis egestas sed tempus urna et pharetra pharetra. Aenean pharetra magna ac placerat vestibulum lectus mauris. Tincidunt lobortis feugiat vivamus at augue. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Viverra justo nec ultrices dui. Risus ultricies tristique nulla aliquet enim tortor at auctor. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Sit amet aliquam id diam maecenas ultricies mi. Consectetur purus ut faucibus pulvinar elementum integer. Sit amet facilisis magna etiam tempor orci. Morbi blandit cursus risus at ultrices mi tempus imperdiet.

Magna fringilla urna porttitor rhoncus dolor purus. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Lorem mollis aliquam ut porttitor. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Neque convallis a cras semper auctor neque vitae tempus quam. Sit amet dictum sit amet justo donec enim diam. Leo vel orci porta non pulvinar neque laoreet. Mattis nunc sed blandit libero volutpat. Duis tristique sollicitudin nibh sit amet commodo nulla. In massa tempor nec feugiat nisl pretium fusce. Faucibus in ornare quam viverra orci sagittis eu volutpat. Proin libero nunc consequat interdum. Mus mauris vitae ultricies leo integer malesuada. Odio euismod lacinia at quis risus. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Ac tortor vitae purus faucibus ornare suspendisse. Augue lacus viverra vitae congue eu consequat ac.
    `
]
}